development:
  adapter: postgresql
  encoding: unicode
  database: mindthedrink_development
  pool: 5
  username: mindthedrink
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: mindthedrink_test
  pool: 5
  username: mindthedrink
  password:
